@echo on
echo Starting IGOOR...
echo Activating virtual environment...
call venv\scripts\activate
echo Setting environment variables...
set "IGOOR_FULLSCREEN=True"
set "IGOOR_DEBUG=True"
echo Starting application...
python main.py
pause